#ifndef EDITOR_TOOL_H
#define EDITOR_TOOL_H

typedef enum
{
    EDITOR_TOOL_SELECT,
    EDITOR_TOOL_OPENING,
    EDITOR_TOOL_WALL,
    EDITOR_TOOL_MEASURE,
    EDITOR_TOOL_SLAB,
    EDITOR_TOOL_SLAB_PENETRATION,
    EDITOR_TOOL_SLAB_REGION,
    EDITOR_TOOL_SLAB_EDGE_REBATE,
    EDITOR_TOOL_SLAB_GEOMETRY,
    EDITOR_TOOL_NOTE,
    EDITOR_TOOL_DIMENSION,
    EDITOR_TOOL_SYMBOL,
    EDITOR_TOOL_VIEW_DIRECTION,
    EDITOR_TOOL_CALLOUT,
    EDITOR_TOOL_REVISION_CLOUD,

    EDITOR_TOOL_COUNT
} EditorTool;

#endif
